/**
 * Version enumeration for the published JSON Schema endpoints.
 *
 * The schemas are served at two URL shapes (see
 * `site/content/docs/configuration/schema.md`):
 *
 * - `/{schema}` — the unversioned "latest" alias.
 * - `/schemas/v{major}.{minor}/{schema}` — the versioned URL that
 *   `create-refrakt` bakes into every scaffolded project's `$schema`.
 *
 * The versioned form is a dynamic route, and the site is fully prerendered
 * (adapter-static, `strict: true`), so every version has to be enumerated at
 * build time. Deriving that list from the package version is what keeps the
 * two in step: a release builds the site from the repo at its own version, so
 * the new version's URL is generated by the same build that publishes it.
 *
 * This is the fix for BUG-004 — the versioned route used to be a single
 * hardcoded `v0.11` directory while `create-refrakt` derived the URL from its
 * own version, so every project scaffolded from v0.12 onward pointed at a 404.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/**
 * Locate `packages/transform` by walking up from the working directory.
 *
 * Not `import.meta.url`-relative: Vite bundles this module into
 * `.svelte-kit/output/server/chunks/`, so at build time the module's own path
 * says nothing about where the repo is. Walking up from the cwd handles both
 * callers — the site build and dev server run from `site/`, the test runner
 * from the repo root.
 */
let transformDir: string | undefined;
function transformPackageDir(): string {
	if (transformDir) return transformDir;
	let dir = resolve(process.cwd());
	for (let up = 0; up < 6; up++) {
		const candidate = resolve(dir, 'packages', 'transform');
		if (existsSync(resolve(candidate, 'package.json'))) return (transformDir = candidate);
		const parent = dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
	throw new Error(
		`Could not locate packages/transform walking up from ${process.cwd()} — the schema endpoints read the published schemas and the version from there.`,
	);
}

export type SchemaName = 'refrakt.config.schema.json' | 'theme-tokens.json';

/** Source file backing each published schema URL. */
const SCHEMA_FILES: Record<SchemaName, string> = {
	'refrakt.config.schema.json': 'refrakt.config.schema.json',
	'theme-tokens.json': 'theme-tokens.schema.json',
};

/** The first release that published a versioned schema URL (WORK-176). Nothing
 *  earlier is served — before v0.11 only the unversioned alias existed. */
const FIRST_VERSIONED_MINOR = 11;

/** Last minor of each *completed* major series, so their URLs keep resolving
 *  after the major rolls over. The in-progress major is derived from the
 *  package version instead. Add an entry here when cutting a new major. */
const COMPLETED_MAJORS: Record<number, number> = {};

/** The version `@refrakt-md/transform` currently ships, as `[major, minor]`. */
export function currentVersion(): [number, number] {
	const pkg = JSON.parse(readFileSync(resolve(transformPackageDir(), 'package.json'), 'utf-8'));
	const [major, minor] = String(pkg.version).split('.').map(Number);
	if (!Number.isInteger(major) || !Number.isInteger(minor)) {
		throw new Error(`@refrakt-md/transform has an unparseable version: ${pkg.version}`);
	}
	return [major, minor];
}

/** `v{major}.{minor}` for the release currently being built — the version the
 *  unversioned "latest" alias resolves to. */
export function currentSchemaVersion(): string {
	const [major, minor] = currentVersion();
	return `v${major}.${minor}`;
}

/**
 * Every version whose URL the site serves: `v0.11` through the version being
 * built, plus every minor of any completed major series.
 *
 * A version that was never published is harmless here — it serves the schema
 * rather than 404ing — but a *missing* one breaks editor validation for every
 * project pinned to it, so the range is deliberately inclusive.
 */
export function publishedSchemaVersions(): string[] {
	const [currentMajor, currentMinor] = currentVersion();
	const versions: string[] = [];

	for (const [major, lastMinor] of Object.entries(COMPLETED_MAJORS)) {
		const m = Number(major);
		const from = m === 0 ? FIRST_VERSIONED_MINOR : 0;
		for (let minor = from; minor <= lastMinor; minor++) versions.push(`v${m}.${minor}`);
	}

	const from = currentMajor === 0 ? FIRST_VERSIONED_MINOR : 0;
	for (let minor = from; minor <= currentMinor; minor++) versions.push(`v${currentMajor}.${minor}`);

	return versions;
}

/**
 * Read a schema and stamp its `$id` to the URL it is being served from, so
 * every endpoint is self-describing. Editors that key off `$id` rather than
 * the fetch URL then resolve `$ref`s against the right identity — without
 * this, the versioned copies would all claim to be whichever version the
 * source file happens to declare.
 *
 * `version` is the `v{major}.{minor}` segment, or `null` for the unversioned
 * alias, which stamps the release currently being built.
 *
 * The source files themselves carry the unversioned `$id`, so the packaged
 * copy shipped inside `@refrakt-md/transform` can't go stale between releases
 * the way a hardcoded version string does.
 */
export function readSchema(name: SchemaName, version: string | null): string {
	const body = JSON.parse(readFileSync(resolve(transformPackageDir(), SCHEMA_FILES[name]), 'utf-8'));
	body.$id = `https://refrakt.md/schemas/${version ?? currentSchemaVersion()}/${name}`;
	return `${JSON.stringify(body, null, '\t')}\n`;
}

/** Response headers shared by every schema endpoint. */
export const SCHEMA_HEADERS = {
	'Content-Type': 'application/schema+json; charset=utf-8',
} as const;
