import {
	runes as coreRunes,
	loadRunePackage,
	mergePackages,
	renderReferenceMarkdown,
	type ReferenceContext,
} from '@refrakt-md/runes';
import { assembleThemeConfig } from '@refrakt-md/transform';

/** Preamble inserted into scaffolded AGENTS.md files. Orients a coding agent
 *  before the machine-generated rune reference that follows. */
const PREAMBLE = `This file is the rune reference for this project, generated by \`refrakt reference dump\`. Both human contributors and coding agents should consult it before authoring or editing \`.md\` content.

**What is a rune?** Runes are Markdoc tags (\`{% ... %}\`) that reinterpret standard Markdown in a semantically meaningful way. A heading inside \`{% nav %}\` becomes a navigation group title; a list inside \`{% recipe %}\` becomes ingredients. The same primitives mean different things based on the enclosing rune — so authoring is just standard Markdown with occasional \`{% rune %}\` wrappers to signal intent.

**How to use this file.** Each section below describes one rune: its attributes (own, inherited, universal), its content model (what child blocks it accepts), and a usage example. When you need a rune not listed here, it's not available in this project.

**Regenerate when the rune set changes.** Run \`refrakt reference dump\` after \`refrakt.config.json\` changes (adding or removing \`packages\`) or after upgrading any \`@refrakt-md/*\` package to keep this file in sync with what the site actually supports. Consider adding \`refrakt reference dump --check\` to CI to catch drift automatically.`;

/** Build an in-memory ReferenceContext from a list of community-package npm names.
 *  Used by the scaffolder to render AGENTS.md before dependencies are installed,
 *  so it must only import from packages that create-refrakt itself depends on. */
export async function buildScaffoldReferenceContext(packages: string[]): Promise<ReferenceContext> {
	const allRunes: Record<string, any> = { ...coreRunes };
	let fixtures: Record<string, string> = {};
	const source: Record<string, string> = {};

	for (const name of Object.keys(coreRunes)) {
		source[name] = 'core';
	}

	if (packages.length > 0) {
		const loaded = await Promise.all(packages.map(name => loadRunePackage(name)));
		const coreRuneNames = new Set(Object.keys(coreRunes));
		const merged = mergePackages(loaded, coreRuneNames);

		const runeToNpm: Record<string, string> = {};
		for (const pkg of loaded) {
			for (const name of Object.keys(pkg.runes)) {
				runeToNpm[name] = pkg.npmName;
			}
		}

		for (const [name, rune] of Object.entries(merged.runes)) {
			allRunes[name] = rune;
			source[name] = runeToNpm[name] ?? 'package';
		}
		fixtures = { ...fixtures, ...merged.fixtures };

		// Assemble theme config so packages register their attribute presets.
		assembleThemeConfig({
			coreConfig: (await import('@refrakt-md/runes')).baseConfig,
			packageRunes: merged.themeRunes,
			packageIcons: merged.themeIcons,
			packageBackgrounds: merged.themeBackgrounds,
			provenance: merged.provenance,
		});
	}

	return { runes: allRunes, fixtures, source };
}

/** Render AGENTS.md for a fresh scaffold. Returns the markdown string. */
export async function renderScaffoldAgentsMd(packages: string[]): Promise<string> {
	const ctx = await buildScaffoldReferenceContext(packages);
	return renderReferenceMarkdown(ctx, { preamble: PREAMBLE });
}
