import { describe, it, expect } from 'vitest';
import { parse, findTag, findAllTags } from './helpers.js';
import { collectJsonLd } from '../src/seo.js';

describe('accordion tag', () => {
	it('should convert headings to accordion items', () => {
		const result = parse(`{% accordion %}
## First Section

Content for first section.

## Second Section

Content for second section.
{% /accordion %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();
		expect(acc!.name).toBe('section');

		const items = findAllTags(acc!, t => t.attributes['data-rune'] === 'accordion-item');
		expect(items.length).toBe(2);

		const firstName = findTag(items[0], t => t.name === 'summary' && t.attributes['data-field'] === 'name');
		expect(firstName).toBeDefined();
		expect(firstName!.children).toContain('First Section');
	});

	it('should work with faq alias', () => {
		const result = parse(`{% faq %}
## What is refrakt.md?

A content framework.

## How do I install it?

Run npm install.
{% /faq %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();
	});

	it('should support explicit accordion-item tags', () => {
		const result = parse(`{% accordion %}
{% accordion-item name="Section One" %}
Content one.
{% /accordion-item %}

{% accordion-item name="Section Two" %}
Content two.
{% /accordion-item %}
{% /accordion %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();

		const items = findAllTags(acc!, t => t.attributes['data-rune'] === 'accordion-item');
		expect(items.length).toBe(2);
	});

	it('should wrap items in a container div', () => {
		const result = parse(`{% accordion %}
{% accordion-item name="Item" %}
Content.
{% /accordion-item %}
{% /accordion %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();

		const container = findTag(acc!, t => t.name === 'div' && t.attributes['data-name'] === 'items');
		expect(container).toBeDefined();
	});

	it('should auto-detect heading level', () => {
		const result = parse(`{% accordion %}
## Item One
Content one.

## Item Two
Content two.
{% /accordion %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();

		const items = findAllTags(acc!, t => t.attributes['data-rune'] === 'accordion-item');
		expect(items.length).toBe(2);

		const firstName = findTag(items[0], t => t.name === 'summary' && t.attributes['data-field'] === 'name');
		expect(firstName).toBeDefined();
		expect(firstName!.children).toContain('Item One');
	});

	it('should auto-detect h3 heading level', () => {
		const result = parse(`{% accordion %}
### Question One
Answer one.

### Question Two
Answer two.

### Question Three
Answer three.
{% /accordion %}`);

		const acc = findTag(result as any, t => t.attributes['data-rune'] === 'accordion');
		expect(acc).toBeDefined();

		const items = findAllTags(acc!, t => t.attributes['data-rune'] === 'accordion-item');
		expect(items.length).toBe(3);
	});
});

describe('an accordion with nothing in it', () => {
	it('renders nothing rather than an empty FAQPage', () => {
		// Reachable since a shared block can wrap items generated by a
		// `{% data %}` whose result is legitimately empty (BUG-011): the block
		// cannot know in advance whether there will be any. An empty
		// `typeof="FAQPage"` is structured data claiming questions it does not
		// have (WORK-548).
		const result = parse('{% accordion %}{% /accordion %}');
		expect(JSON.stringify(result)).not.toContain('FAQPage');
		expect(findTag(result, (t) => t.attributes?.['data-rune'] === 'accordion')).toBeUndefined();
	});

	it('still renders when it has a header but no items', () => {
		// A header is authored content — dropping it would lose something the
		// author wrote, which is a different case from "the query found nothing".
		const result = parse('{% accordion %}\n# Questions\n{% /accordion %}');
		expect(findTag(result, (t) => t.attributes?.['data-rune'] === 'accordion')).toBeDefined();
	});
});

describe('schema="none" (WORK-552)', () => {
	const SRC = (attrs = '') => `{% accordion ${attrs} %}\n## Q\n\nA.\n\n## Q2\n\nB.\n{% /accordion %}`;

	it('emits FAQPage and Question by default', () => {
		const json = JSON.stringify(parse(SRC()));
		expect(json).toContain('FAQPage');
		expect(json).toContain('Question');
	});

	it('emits no schema at all when set to "none"', () => {
		const json = JSON.stringify(parse(SRC('schema="none"')));
		expect(json).not.toContain('FAQPage');
		expect(json).not.toContain('Question');
		// The items declare `Answer` independently too — the strip is subtree-wide.
		expect(json).not.toContain('Answer');
	});

	it('strips the `property` half as well, not just `typeof`', () => {
		// `collectJsonLd` reads `typeof`, but a stray `property` on a child would
		// still attach to whatever ancestor type survives.
		const json = JSON.stringify(parse(SRC('schema="none"')));
		expect(json).not.toContain('"property"');
	});

	it('leaves the rendered content identical', () => {
		// Compare the trees with the schema attributes removed from both, rather
		// than regexing the serialised JSON — a string strip leaves dangling
		// commas and reports a difference that is not there.
		const bare = (node: unknown): unknown => {
			if (Array.isArray(node)) return node.map(bare);
			if (!node || typeof node !== 'object') return node;
			const { typeof: _t, property: _p, ...attrs } = (node as any).attributes ?? {};
			return { ...(node as any), attributes: attrs, children: ((node as any).children ?? []).map(bare) };
		};
		expect(bare(parse(SRC('schema="none"')))).toEqual(bare(parse(SRC())));
	});

	it('produces no JSON-LD, not merely bare HTML attributes', () => {
		// The failure worth guarding: a strip that runs too late cleans the
		// markup and leaves the structured data already harvested.
		expect(collectJsonLd(parse(SRC('schema="none"')))).toEqual([]);
		expect(collectJsonLd(parse(SRC()))).not.toEqual([]);
	});
});
