import {
  useSchema,
  Page, PageComponent, PageSectionComponent,
  DocPage, DocPageComponent,
  Headings, HeadingsComponent,
  Hint, HintComponent,
  Menu, MenuComponent,
  SequentialPagination, SequentialPaginationComponent,
  Steps, StepsComponent,
  Step, StepComponent,
  TableOfContents, TableOfContentsComponent,
  Topic, TopicComponent,
  TabGroup, TabGroupComponent,
  Tab, TabComponent,
  TabPanel, TabPanelComponent,
  Footer, FooterComponent,
  MusicPlaylist, MusicPlaylistComponent,
  MusicRecording, MusicRecordingComponent,
  CallToAction, CallToActionComponent,
  LinkItem, LinkItemComponent,
  Command, CommandComponent,
  Feature, FeatureComponent,
  FeatureDefinition, FeatureDefinitionComponent,
  Editor, EditorComponent,
  Pricing, PricingComponent,
  Tier, TierComponent,
  Grid, GridComponent,
  Error, ErrorComponent,
  DebugInfo, DebugInfoComponent,
  PageSection,
} from '@refract-md/types';

export const schema = {
  Page: useSchema(Page).defineType<PageComponent>('Page'),
  PageSection: useSchema(PageSection).defineType<PageSectionComponent>('PageSection'),
  DocPage: useSchema(DocPage).defineType<DocPageComponent>('DocPage'),
  Headings: useSchema(Headings).defineType<HeadingsComponent>('Headings'),
  Hint: useSchema(Hint).defineType<HintComponent>('Hint'),
  Menu: useSchema(Menu).defineType<MenuComponent>('Menu'),
  SequentialPagination: useSchema(SequentialPagination).defineType<SequentialPaginationComponent>('SequentialPagination'),
  Steps: useSchema(Steps).defineType<StepsComponent>('Steps'),
  Step: useSchema(Step).defineType<StepComponent>('Step'),
  TableOfContents: useSchema(TableOfContents).defineType<TableOfContentsComponent>('TableOfContents'),
  Topic: useSchema(Topic).defineType<TopicComponent>('Topic'),
  TabGroup: useSchema(TabGroup).defineType<TabGroupComponent>('TabGroup'),
  Tab: useSchema(Tab).defineType<TabComponent>('Tab'),
  TabPanel: useSchema(TabPanel).defineType<TabPanelComponent>('TabPanel'),
  Footer: useSchema(Footer).defineType<FooterComponent>('Footer'),
  MusicPlaylist: useSchema(MusicPlaylist).defineType<MusicPlaylistComponent>('MusicPlaylist', {
    schema: 'http://schema.org/',
    MusicPlaylist: 'schema:MusicPlaylist',
    headline: 'schema:name schema:headline',
    image: 'schema:image',
    track: 'schema:track',
  }),
  MusicRecording: useSchema(MusicRecording).defineType<MusicRecordingComponent>('MusicRecording', {
    schema: 'http://schema.org/',
    MusicRecording: 'schema:MusicRecording',
    name: 'schema:name',
    byArtist: 'schema:byArtist',
    duration: 'schema:duration',
    copyrightYear: 'schema:copyrightYear',
  }),
  CallToAction: useSchema(CallToAction).defineType<CallToActionComponent>('CallToAction'),
  LinkItem: useSchema(LinkItem).defineType<LinkItemComponent>('LinkItem'),
  Command: useSchema(Command).defineType<CommandComponent>('Command'),
  Feature: useSchema(Feature).defineType<FeatureComponent>('Feature'),
  FeatureDefinition: useSchema(FeatureDefinition).defineType<FeatureDefinitionComponent>('FeatureDefinition'),
  Editor: useSchema(Editor).defineType<EditorComponent>('Editor'),
  Pricing: useSchema(Pricing).defineType<PricingComponent>('Pricing'),
  Tier: useSchema(Tier).defineType<TierComponent>('Tier'),
  FeaturedTier: useSchema(Tier).defineType<TierComponent>('FeaturedTier'),
  Grid: useSchema(Grid).defineType<GridComponent>('Grid'),
  Error: useSchema(Error).defineType<ErrorComponent>('Error'),
  DebugInfo: useSchema(DebugInfo).defineType<DebugInfoComponent>('DebugInfo'),
}
